### ISSUE TITLE
ACNA-337 - Reloading doesn't reload dotenv

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-config#2]
**Describe the bug**
write a .env, load config, rewrite .env, reload => same config as in first load

The issue is within dotenv where process.env vars have prio over the .env file, meaning that once a .env file is loaded to process.env, we cannot override:
See https://github.com/motdotla/dotenv/issues/122

**Expected behavior**
Not sure here, do we want to/ can we support env variable reload?

**Comment by goya** [comment]
you are indeed correct as .env files don’t override env variables that already exist.

we might need a list of previously hoisted env variables so we can roll back or allow overwriting.

**Comment by moritzraho** [comment]
@goya yes good idea
